name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2, 8.3]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup composer
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          php-version: ${{ matrix.php }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute tests (Unit and Feature tests) via Pest
        run: vendor/bin/pest
